<a href="https://colab.research.google.com/github/harivign/dataset-cleaning-using-pandas-/blob/main/dataset_cleaning_using_pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#I have cleaning of this data using pandas and covert for mechine learning (change all string to float in last) its help to real data to ml

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("train-chennai-sale.csv") # use your file path here
df

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df.columns

Index(['PRT_ID', 'AREA', 'INT_SQFT', 'DATE_SALE', 'DIST_MAINROAD', 'N_BEDROOM',
       'N_BATHROOM', 'N_ROOM', 'SALE_COND', 'PARK_FACIL', 'DATE_BUILD',
       'BUILDTYPE', 'UTILITY_AVAIL', 'STREET', 'MZZONE', 'QS_ROOMS',
       'QS_BATHROOM', 'QS_BEDROOM', 'QS_OVERALL', 'REG_FEE', 'COMMIS',
       'SALES_PRICE'],
      dtype='object')

In [ ]:
pd.set_option("display.max_columns",None)
df

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,15-01-1962,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,11-04-1995,Others,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,01-09-1978,House,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,11-08-1977,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,24-07-1961,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PRT_ID         7109 non-null   object
 1   AREA           7109 non-null   object
 2   INT_SQFT       7109 non-null   int64
 3   DATE_SALE      7109 non-null   object
 4   DIST_MAINROAD  7109 non-null   int64
 5   N_BEDROOM      7108 non-null   float64
 6   N_BATHROOM     7104 non-null   float64
 7   N_ROOM         7109 non-null   int64
 8   SALE_COND      7109 non-null   object
 9   PARK_FACIL     7109 non-null   object
 10  DATE_BUILD     7109 non-null   object
 11  BUILDTYPE      7109 non-null   object
 12  UTILITY_AVAIL  7109 non-null   object
 13  STREET         7109 non-null   object
 14  MZZONE         7109 non-null   object
 15  QS_ROOMS       7109 non-null   float64
 16  QS_BATHROOM    7109 non-null   float64
 17  QS_BEDROOM     7109 non-null   float64
 18  QS_OVERALL     7061 non-null   float64
 19  REG_FEE        7109 non-null   int64
 20  COMMIS         7109 non-null   int64
 21  SALES_PRICE    7109 non-null   int64
dtypes: float64(6), int64(6), object(10)
memory usage: 1.2+ MB

In [ ]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

PRT_ID ['P03210' 'P09411' 'P01812' ... 'P09594' 'P06508' 'P09794']
AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'TNagar' 'T Nagar' 'Chrompt' 'Chrmpet' 'Karapakam' 'Ana Nagar' 'Chormpet'
 'Adyr' 'Velchery' 'Ann Nagar' 'KKNagar']
DATE_SALE ['04-05-2011' '19-12-2006' '04-02-2012' ... '28-03-2014' '25-08-2006'
 '13-07-2005']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale' 'Ab Normal'
 'Partiall' 'Adj Land' 'PartiaLl']
PARK_FACIL ['Yes' 'No' 'Noo']
DATE_BUILD ['15-05-1967' '22-12-1995' '09-02-1992' ... '01-09-1978' '11-08-1977'
 '24-07-1961']
BUILDTYPE ['Commercial' 'Others' 'Other' 'House' 'Comercial']
UTILITY_AVAIL ['AllPub' 'ELO' 'NoSewr ' 'NoSeWa' 'All Pub']
STREET ['Paved' 'Gravel' 'No Access' 'Pavd' 'NoAccess']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [ ]:
df['AREA']=df["AREA"].apply(lambda i:"Anna Nagar" if (i == "Ana Nagar" or i == "Ann Nagar") else i)
df['AREA']=df["AREA"].apply(lambda i:"Karapakkam" if (i == "Karapakam" ) else i)
df['AREA']=df["AREA"].apply(lambda i:"Adyar" if (i == "Adyr") else i)
df['AREA']=df["AREA"].apply(lambda i:"Velachery" if (i == "Velchery") else i)
df['AREA']=df["AREA"].apply(lambda i:"Chrompet" if (i == "Chrompt" or i == "Chrmpet" or i =="Chormpet") else i)
df['AREA']=df["AREA"].apply(lambda i:"KK Nagar" if (i == "KKNagar") else i)
df['AREA']=df["AREA"].apply(lambda i:"T Nagar" if (i == "TNagar") else i)
df['SALE_COND']=df["SALE_COND"].apply(lambda i:"AbNormal" if (i == "Ab Normal") else i)
df['SALE_COND']=df["SALE_COND"].apply(lambda i:"Partial" if (i == "Partiall" or i == "PartiaLl") else i)
df['SALE_COND']=df["SALE_COND"].apply(lambda i:"AdjLand" if (i == "Adj Land") else i)
df['PARK_FACIL']=df["PARK_FACIL"].apply(lambda i:"No" if (i == "Noo") else i)
df['BUILDTYPE']=df["BUILDTYPE"].apply(lambda i:"Commercial" if (i == "Comercial") else i)
df['BUILDTYPE']=df["BUILDTYPE"].apply(lambda i:"Others" if (i == "Other") else i)
df['UTILITY_AVAIL']=df["UTILITY_AVAIL"].apply(lambda i:"No sewage" if (i == "NoSewr " or i == "NoSeWa") else i)  #sewage
df['UTILITY_AVAIL']=df["UTILITY_AVAIL"].apply(lambda i:"AllPub" if (i == "All Pub") else i)
df['STREET']=df['STREET'].apply(lambda i:"Paved" if ( i == "Pavd") else i )
df['STREET']=df['STREET'].apply(lambda i:"No Access" if ( i == "NoAccess") else i )

In [ ]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

PRT_ID ['P03210' 'P09411' 'P01812' ... 'P09594' 'P06508' 'P09794']
AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
DATE_SALE ['04-05-2011' '19-12-2006' '04-02-2012' ... '28-03-2014' '25-08-2006'
 '13-07-2005']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
PARK_FACIL ['Yes' 'No']
DATE_BUILD ['15-05-1967' '22-12-1995' '09-02-1992' ... '01-09-1978' '11-08-1977'
 '24-07-1961']
BUILDTYPE ['Commercial' 'Others' 'House']
UTILITY_AVAIL ['AllPub' 'ELO' 'No sewage']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PRT_ID         7109 non-null   object
 1   AREA           7109 non-null   object
 2   INT_SQFT       7109 non-null   int64
 3   DATE_SALE      7109 non-null   object
 4   DIST_MAINROAD  7109 non-null   int64
 5   N_BEDROOM      7108 non-null   float64
 6   N_BATHROOM     7104 non-null   float64
 7   N_ROOM         7109 non-null   int64
 8   SALE_COND      7109 non-null   object
 9   PARK_FACIL     7109 non-null   object
 10  DATE_BUILD     7109 non-null   object
 11  BUILDTYPE      7109 non-null   object
 12  UTILITY_AVAIL  7109 non-null   object
 13  STREET         7109 non-null   object
 14  MZZONE         7109 non-null   object
 15  QS_ROOMS       7109 non-null   float64
 16  QS_BATHROOM    7109 non-null   float64
 17  QS_BEDROOM     7109 non-null   float64
 18  QS_OVERALL     7061 non-null   float64
 19  REG_FEE        7109 non-null   int64
 20  COMMIS         7109 non-null   int64
 21  SALES_PRICE    7109 non-null   int64
dtypes: float64(6), int64(6), object(10)
memory usage: 1.2+ MB

In [ ]:
df['DATE_SALE']=pd.to_datetime(df["DATE_SALE"],format="%d-%m-%Y")
df['DATE_BUILD']=pd.to_datetime(df["DATE_BUILD"],format="%d-%m-%Y")

In [ ]:
df.set_index("PRT_ID",inplace=True) #dont run 2 times

In [ ]:
df.columns

Index(['AREA', 'INT_SQFT', 'DATE_SALE', 'DIST_MAINROAD', 'N_BEDROOM',
       'N_BATHROOM', 'N_ROOM', 'SALE_COND', 'PARK_FACIL', 'DATE_BUILD',
       'BUILDTYPE', 'UTILITY_AVAIL', 'STREET', 'MZZONE', 'QS_ROOMS',
       'QS_BATHROOM', 'QS_BEDROOM', 'QS_OVERALL', 'REG_FEE', 'COMMIS',
       'SALES_PRICE'],
      dtype='object')

In [ ]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Others,No sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,1979-10-13,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,Yes,1995-04-11,Others,No sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,House,No sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,Yes,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,Yes,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7109 entries, P03210 to P09794
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           7109 non-null   object
 1   INT_SQFT       7109 non-null   int64
 2   DATE_SALE      7109 non-null   datetime64[ns]
 3   DIST_MAINROAD  7109 non-null   int64
 4   N_BEDROOM      7108 non-null   float64
 5   N_BATHROOM     7104 non-null   float64
 6   N_ROOM         7109 non-null   int64
 7   SALE_COND      7109 non-null   object
 8   PARK_FACIL     7109 non-null   object
 9   DATE_BUILD     7109 non-null   datetime64[ns]
 10  BUILDTYPE      7109 non-null   object
 11  UTILITY_AVAIL  7109 non-null   object
 12  STREET         7109 non-null   object
 13  MZZONE         7109 non-null   object
 14  QS_ROOMS       7109 non-null   float64
 15  QS_BATHROOM    7109 non-null   float64
 16  QS_BEDROOM     7109 non-null   float64
 17  QS_OVERALL     7061 non-null   float64
 18  REG_FEE        7109 non-null   int64
 19  COMMIS         7109 non-null   int64
 20  SALES_PRICE    7109 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(6), object(7)
memory usage: 1.2+ MB

In [ ]:
df1=df.copy()

In [ ]:
df["PARK_FACIL"]=df["PARK_FACIL"].replace({"Yes":1})
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Others,No sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1,1979-10-13,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1,1995-04-11,Others,No sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,House,No sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df["PARK_FACIL"]=df["PARK_FACIL"].map({"Yes":1})
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1.0,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,NaN,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1.0,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,NaN,1988-03-18,Others,No sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1.0,1979-10-13,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,NaN,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1.0,1995-04-11,Others,No sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,NaN,1978-09-01,House,No sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1.0,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1.0,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df=df1.copy()

In [ ]:
df["PARK_FACIL"]=df["PARK_FACIL"].map({"Yes":1,"No":0})
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,0,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,0,1988-03-18,Others,No sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1,1979-10-13,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,0,1962-01-15,Others,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1,1995-04-11,Others,No sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,0,1978-09-01,House,No sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1,1961-07-24,Others,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7109 entries, P03210 to P09794
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           7109 non-null   object
 1   INT_SQFT       7109 non-null   int64
 2   DATE_SALE      7109 non-null   datetime64[ns]
 3   DIST_MAINROAD  7109 non-null   int64
 4   N_BEDROOM      7108 non-null   float64
 5   N_BATHROOM     7104 non-null   float64
 6   N_ROOM         7109 non-null   int64
 7   SALE_COND      7109 non-null   object
 8   PARK_FACIL     7109 non-null   int64
 9   DATE_BUILD     7109 non-null   datetime64[ns]
 10  BUILDTYPE      7109 non-null   object
 11  UTILITY_AVAIL  7109 non-null   object
 12  STREET         7109 non-null   object
 13  MZZONE         7109 non-null   object
 14  QS_ROOMS       7109 non-null   float64
 15  QS_BATHROOM    7109 non-null   float64
 16  QS_BEDROOM     7109 non-null   float64
 17  QS_OVERALL     7061 non-null   float64
 18  REG_FEE        7109 non-null   int64
 19  COMMIS         7109 non-null   int64
 20  SALES_PRICE    7109 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(7), object(6)
memory usage: 1.2+ MB

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
encode=OrdinalEncoder()

In [ ]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
BUILDTYPE ['Commercial' 'Others' 'House']
UTILITY_AVAIL ['AllPub' 'ELO' 'No sewage']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [ ]:
for i in df.select_dtypes(include=["object"]).columns:
  df[i]=encode.fit_transform(df[[i]])

In [ ]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

In [ ]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,4.0,1004,2011-05-04,131,1.0,1.0,3,0.0,1,1967-05-15,0.0,0.0,2.0,0.0,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,1.0,1986,2006-12-19,26,2.0,1.0,5,0.0,0,1995-12-22,0.0,0.0,0.0,3.0,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,0.0,909,2012-02-04,70,1.0,1.0,3,0.0,1,1992-02-09,0.0,1.0,0.0,4.0,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,6.0,1855,2010-03-13,14,3.0,2.0,5,2.0,0,1988-03-18,2.0,2.0,2.0,2.0,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,4.0,1226,2009-10-05,84,1.0,1.0,3,0.0,1,1979-10-13,2.0,0.0,0.0,1.0,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,4.0,598,2011-01-03,51,1.0,1.0,2,1.0,0,1962-01-15,2.0,1.0,1.0,5.0,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,6.0,1897,2004-04-08,52,3.0,2.0,5,2.0,1,1995-04-11,2.0,2.0,1.0,3.0,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,6.0,1614,2006-08-25,152,2.0,1.0,4,3.0,0,1978-09-01,1.0,2.0,0.0,2.0,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,4.0,787,2009-08-03,40,1.0,1.0,2,4.0,1,1977-08-11,0.0,1.0,2.0,4.0,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,6.0,1896,2005-07-13,156,3.0,2.0,5,4.0,1,1961-07-24,2.0,1.0,2.0,2.0,3.1,3.5,4.3,3.640,349177,79812,9976480

In [ ]:
df1=df.copy()